title: Kids Art & Creations testing
description: Artwork, LEGO builds, and creative fun
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

author:
  name: Our Family

minimal_mistakes_skin: "sunrise"

collections:
  gallery:
    output: true

